### ISSUE TITLE
Only bad proxy

### ISSUE THREAD

**Issue by jeremycwu** [yousefissa/Proxy-Tester#1]
Hi

For some reason any proxy I put in proxy.txt comes up as bad proxy, I tried some of them manually with foxyproxy and the proxies I tested were working fine. Any idea why the output might be wrong?

Thanks and really appreciate the script!

**Comment by yousefissa** [comment]
Ill work on an update

**Comment by PUNTxR** [comment]
I have the same issue. Looking forward to the update!

It only fails when there is no authentication.

**Comment by jeremycwu** [comment]
thanks yousef!!!!

**Comment by yousefissa** [comment]
I know it's been awhile. Thanks for supporting me and keep on the lookout for more updates!
